### ISSUE TITLE
Code for FGDB -> TXT -> SQLite workflow?

### ISSUE THREAD

**Issue by kanedan29** [dylanbeaudette/process-kssl-snapshot#13]
Is there a repo containing code for the FGDB -> TXT -> SQLite workflow? Would be interested in seeing that.

**Comment by dylanbeaudette** [comment]
There is!

https://github.com/ncss-tech/lab-data-delivery/

Nothing in that repository is ready for production use, and all code / data are subject to change. We should have some new snapshots ready for posting to the KSSL website within a month or two.

**Comment by kanedan29** [comment]
Thanks!
